flowchart TD
metricflow_users[MetricFlow.Users]
metricflowweb_userlive_settings[MetricFlowWeb.UserLive.Settings]
metricflowweb_dashboardlive_show[MetricFlowWeb.DashboardLive.Show]
metricflowweb_correlationlive_index[MetricFlowWeb.CorrelationLive.Index]
metricflowweb_ailive_chat[MetricFlowWeb.AiLive.Chat]
metricflow_integrations[MetricFlow.Integrations]
metricflow_datasync[MetricFlow.DataSync]
metricflowweb_ailive_reportgenerator[MetricFlowWeb.AiLive.ReportGenerator]
metricflow_agencies[MetricFlow.Agencies]
metricflow_accounts[MetricFlow.Accounts]
metricflowweb_correlationlive_goals[MetricFlowWeb.CorrelationLive.Goals]
metricflow_correlations[MetricFlow.Correlations]
metricflow_metrics[MetricFlow.Metrics]
metricflowweb_integrationlive_synchistory[MetricFlowWeb.IntegrationLive.SyncHistory]
metricflow_invitations[MetricFlow.Invitations]
metricflowweb_agencylive_settings[MetricFlowWeb.AgencyLive.Settings]
metricflow_ai[MetricFlow.Ai]
metricflow_dashboards[MetricFlow.Dashboards]
metricflowweb_visualizationlive_editor[MetricFlowWeb.VisualizationLive.Editor]
metricflowweb_ailive_insights[MetricFlowWeb.AiLive.Insights]
metricflowweb_dashboardlive_index[MetricFlowWeb.DashboardLive.Index]
metricflowweb_reportlive_index[MetricFlowWeb.ReportLive.Index]
metricflowweb_reportlive_show[MetricFlowWeb.ReportLive.Show]
metricflowweb_userlive_settings --> metricflow_users
metricflow_ai --> metricflow_accounts
metricflow_ai --> metricflow_correlations
metricflowweb_dashboardlive_show --> metricflow_dashboards
metricflow_ai --> metricflow_users
metricflow_datasync --> metricflow_integrations
metricflowweb_correlationlive_index --> metricflow_correlations
metricflowweb_ailive_chat --> metricflow_ai
metricflow_integrations --> metricflow_users
metricflow_datasync --> metricflow_metrics
metricflow_datasync --> metricflow_users
metricflowweb_ailive_reportgenerator --> metricflow_ai
metricflow_agencies --> metricflow_accounts
metricflow_agencies --> metricflow_users
metricflowweb_correlationlive_goals --> metricflow_metrics
metricflow_correlations --> metricflow_metrics
metricflow_correlations --> metricflow_integrations
metricflow_correlations --> metricflow_users
metricflow_metrics --> metricflow_users
metricflowweb_integrationlive_synchistory --> metricflow_datasync
metricflow_correlations --> metricflow_accounts
metricflow_invitations --> metricflow_accounts
metricflow_invitations --> metricflow_users
metricflow_dashboards --> metricflow_users
metricflowweb_agencylive_settings --> metricflow_agencies
metricflow_ai --> metricflow_metrics
metricflow_dashboards --> metricflow_metrics
metricflow_dashboards --> metricflow_integrations
metricflowweb_visualizationlive_editor --> metricflow_dashboards
metricflowweb_ailive_insights --> metricflow_ai
metricflowweb_dashboardlive_index --> metricflow_dashboards
metricflow_accounts --> metricflow_users
metricflowweb_reportlive_index --> metricflow_metrics
metricflowweb_reportlive_index --> metricflow_dashboards
metricflowweb_reportlive_show --> metricflow_metrics
metricflowweb_reportlive_show --> metricflow_dashboards