ignored_paths:
  - lib/metric_flow/repo.ex
  - lib/metric_flow/mailer.ex
  - lib/metric_flow/users.ex
  - lib/metric_flow/vault.ex
  - lib/metric_flow/users/*
  - lib/metric_flow_web/application.ex
  - lib/metric_flow_web/endpoint.ex
  - lib/metric_flow_web/router.ex
  - lib/metric_flow_web/telemetry.ex
  - lib/metric_flow_web/gettext.ex
  - lib/metric_flow_web/components/core_components.ex
  - lib/metric_flow_web/components/layouts.ex
  - lib/metric_flow_web/controllers/error_*
  - lib/metric_flow_web/controllers/page_*
  - lib/metric_flow.ex
  - lib/metric_flow_web.ex
  - lib/metric_flow_web/prom_ex.ex
  - lib/metric_flow_web/user_auth.ex
  - lib/metric_flow_web/controllers/user_session_controller.ex
  - lib/metric_flow/release.ex
  - lib/metric_flow/encrypted/*
  - lib/metric_flow_web/live/user_live/confirmation.ex
  - lib/metric_flow_web/controllers/health_controller.ex
  - lib/metric_flow_web/live/feedback_widget.ex
  - lib/metric_flow/codemyspec/*
