defmodule MetricFlowWeb.SupportWidgetLive do
  @moduledoc """
  Always-on support widget for every visitor, signed in or not — a sticky
  nested LiveView with two clear intents:

    * **Chat** — a live conversation with a CodeMySpec operator.
    * **Report a problem** — file an issue (title/description/severity) that
      lands in the project's CodeMySpec issue queue.

  Both ride the same per-user `WidgetClient` Slipstream connection, authenticated
  by the project deploy key — the key never reaches the browser. Chat relays
  `send_message`/`new_message`; "Report a problem" pushes a `submit_feedback`
  event on the same conversation topic. Generated by `mix cms_gen.support_widget`.
  """

  use MetricFlowWeb, :live_view

  on_mount {MetricFlowWeb.UserAuth, :mount_current_scope}

  alias MetricFlow.CodeMySpec.Widget

  @impl true
  def mount(_params, session, socket) do
    user = socket.assigns[:current_scope] && socket.assigns.current_scope.user

    # The visitor who never signed up is the one with the most to say about
    # bouncing off the product, and asking them to register first loses exactly
    # that — so the widget renders for everyone. Their identity is derived from
    # the session, which keeps one client per browser rather than one per page
    # view, and claims nothing about who they are.
    identity = identity(user, session)

    socket =
      socket
      |> assign(:user, user)
      |> assign(:identity, identity)
      # "pending", not "unavailable": on a dead render nothing has tried to
      # connect yet, and saying "unavailable" there means the marker reads the
      # same whether the backend is up or down — which is no signal at all.
      |> assign(:widget_state, "pending")
      |> assign(:open, false)
      |> assign(:tab, :chat)
      |> assign(:messages, [])
      |> assign(:chat_body, "")
      |> assign(:pending_attachments, [])
      |> assign(:chat_pending_meta, nil)
      |> assign(:fb_submitted, false)
      |> assign(:fb_error, nil)
      |> assign(:fb_title, "")
      |> assign(:fb_description, "")
      |> assign(:fb_severity, "medium")
      |> assign(:screenshot_key, nil)
      |> assign(:screenshot_content_type, nil)
      |> assign(:pending_content_type, nil)
      |> assign(:capturing, false)

    # Only for a real browser session. A plain GET — a crawler, or CodeMySpec's
    # own presence probe — renders the launcher and opens nothing, so scraping
    # the site cannot spawn connections.
    if connected?(socket) do
      Widget.ensure_started(identity.id, identity.email, MetricFlowWeb.Endpoint.url())
      Phoenix.PubSub.subscribe(MetricFlow.PubSub, Widget.topic(identity.id))
      %{messages: messages, connected: connected} = Widget.state(identity.id)

      {:ok,
       socket
       |> assign(:messages, messages)
       |> assign(:widget_state, widget_state(connected)), layout: false}
    else
      {:ok, socket, layout: false}
    end
  end

  # Signed-in users keep their own thread across devices; a visitor gets one
  # per browser session. `session_id` is whatever the host app already puts in
  # the session; the fallback keeps this working in apps that put nothing.
  defp identity(%{id: id, email: email}, _session), do: %{id: to_string(id), email: email}

  defp identity(nil, session) do
    id = session["live_socket_id"] || session["_csrf_token"] || "visitor"
    digest = :crypto.hash(:sha256, id) |> Base.url_encode64(padding: false) |> binary_part(0, 16)
    %{id: "visitor-" <> digest, email: "visitor-#{digest}@visitors.invalid"}
  end

  defp widget_state(true), do: "connected"
  defp widget_state(false), do: "unavailable"

  @impl true
  def handle_event("toggle", _params, socket) do
    {:noreply, update(socket, :open, &(!&1))}
  end

  def handle_event("switch_tab", %{"tab" => tab}, socket) do
    {:noreply, assign(socket, :tab, tab_atom(tab))}
  end

  def handle_event("send", %{"message" => %{"body" => body}}, socket) do
    body = String.trim(body)
    attachments = socket.assigns.pending_attachments

    if body != "" or attachments != [] do
      Widget.send_message(socket.assigns.identity.id, body, attachments)
    end

    {:noreply, socket |> assign(:pending_attachments, []) |> assign(:chat_body, "")}
  end

  def handle_event("chat_change", %{"message" => %{"body" => body}}, socket) do
    {:noreply, assign(socket, :chat_body, body)}
  end

  # A file was picked in the chat composer — get a presigned URL to upload it to.
  def handle_event("request_chat_upload", %{"content_type" => ct, "filename" => filename}, socket) do
    Widget.request_chat_upload(socket.assigns.identity.id, ct, filename)

    {:noreply,
     assign(socket, :chat_pending_meta, %{"filename" => filename, "content_type" => ct})}
  end

  # The browser finished uploading the file to S3 — stage it for the next send.
  def handle_event("chat_uploaded", %{"s3_key" => key} = params, socket) do
    attachment = %{
      "s3_key" => key,
      "filename" => params["filename"],
      "content_type" => params["content_type"],
      "size" => params["size"]
    }

    {:noreply,
     socket
     |> update(:pending_attachments, &(&1 ++ [attachment]))
     |> assign(:chat_pending_meta, nil)}
  end

  def handle_event("chat_upload_failed", _params, socket) do
    {:noreply, assign(socket, :chat_pending_meta, nil)}
  end

  def handle_event("remove_attachment", %{"key" => key}, socket) do
    {:noreply,
     update(socket, :pending_attachments, fn atts -> Enum.reject(atts, &(&1["s3_key"] == key)) end)}
  end

  def handle_event("load_older", _params, socket) do
    with before when is_binary(before) <- oldest_cursor(socket.assigns.messages) do
      Widget.load_older(socket.assigns.identity.id, before)
    end

    {:noreply, socket}
  end

  # Track the report fields in assigns so a screenshot-capture re-render doesn't
  # wipe what the user typed (uncontrolled inputs get reset on patch).
  def handle_event("fb_change", params, socket) do
    {:noreply,
     socket
     |> assign(:fb_title, params["title"] || "")
     |> assign(:fb_description, params["description"] || "")
     |> assign(:fb_severity, params["severity"] || "medium")}
  end

  def handle_event("capture_start", _params, socket) do
    {:noreply, assign(socket, :capturing, true)}
  end

  # The browser captured a screenshot and wants a presigned URL to upload it to.
  def handle_event("request_screenshot_upload", %{"content_type" => content_type}, socket) do
    Widget.request_screenshot_upload(socket.assigns.identity.id, content_type)

    {:noreply, assign(socket, :pending_content_type, content_type)}
  end

  # The browser finished uploading the bytes straight to S3 — keep only the key.
  def handle_event("screenshot_uploaded", %{"s3_key" => key} = params, socket) do
    {:noreply,
     socket
     |> assign(:screenshot_key, key)
     |> assign(
       :screenshot_content_type,
       params["content_type"] || socket.assigns.pending_content_type
     )
     |> assign(:capturing, false)}
  end

  def handle_event("screenshot_failed", _params, socket) do
    {:noreply, assign(socket, :capturing, false)}
  end

  def handle_event("remove_screenshot", _params, socket) do
    {:noreply, socket |> assign(:screenshot_key, nil) |> assign(:screenshot_content_type, nil)}
  end

  def handle_event("submit_feedback", params, socket) do
    title = String.trim(params["title"] || socket.assigns.fb_title)
    description = String.trim(params["description"] || socket.assigns.fb_description)
    severity = params["severity"] || socket.assigns.fb_severity

    if title == "" do
      {:noreply, assign(socket, :fb_error, "Please add a short summary.")}
    else
      Widget.submit_feedback(socket.assigns.identity.id, %{
        "title" => title,
        "description" => description,
        "severity" => severity,
        "screenshot_key" => socket.assigns.screenshot_key,
        "screenshot_content_type" => socket.assigns.screenshot_content_type
      })

      {:noreply,
       socket
       |> assign(:fb_submitted, true)
       |> assign(:fb_error, nil)
       |> assign(:fb_title, "")
       |> assign(:fb_description, "")
       |> assign(:fb_severity, "medium")
       |> assign(:screenshot_key, nil)
       |> assign(:screenshot_content_type, nil)}
    end
  end

  def handle_event("reset_feedback", _params, socket) do
    {:noreply, assign(socket, :fb_submitted, false)}
  end

  @impl true
  def handle_info({:connected, connected}, socket) do
    {:noreply, assign(socket, :widget_state, widget_state(connected))}
  end

  def handle_info({:new_message, payload}, socket) do
    {:noreply, assign(socket, :messages, socket.assigns.messages ++ [payload])}
  end

  def handle_info({:messages, messages}, socket) do
    {:noreply, assign(socket, :messages, messages)}
  end

  # CodeMySpec returned a presigned URL — tell the browser hook to PUT the bytes.
  def handle_info({:screenshot_upload, url, key}, socket) do
    {:noreply,
     push_event(socket, "screenshot_upload_url", %{
       url: url,
       s3_key: key,
       content_type: socket.assigns.pending_content_type || "image/png"
     })}
  end

  # CodeMySpec returned a presigned URL for a chat attachment — tell the hook to
  # PUT the file the browser is holding.
  def handle_info({:chat_upload, url, key}, socket) do
    meta = socket.assigns.chat_pending_meta || %{}

    {:noreply,
     push_event(socket, "chat_upload_url", %{
       url: url,
       s3_key: key,
       content_type: meta["content_type"] || "application/octet-stream"
     })}
  end

  def handle_info(_message, socket), do: {:noreply, socket}

  defp oldest_cursor([%{"inserted_at" => ts} | _]), do: ts
  defp oldest_cursor(_), do: nil

  defp tab_atom("feedback"), do: :feedback
  defp tab_atom(_), do: :chat

  defp image_attachment?(%{"content_type" => ct}) when is_binary(ct),
    do: String.starts_with?(ct, "image/")

  defp image_attachment?(_attachment), do: false

  defp message_attachments(%{"attachments" => list}) when is_list(list), do: list
  defp message_attachments(_message), do: []

  @impl true
  def render(assigns) do
    ~H"""
    <div
      id="codemyspec-support-widget"
      data-cms-widget
      data-cms-widget-state={@widget_state}
      phx-hook=".CmsScreenshot"
      class="fixed bottom-4 right-4 z-50"
    >
      <script :type={Phoenix.LiveView.ColocatedHook} name=".CmsScreenshot">
        export default {
          mounted() {
            this.el.addEventListener("click", async (e) => {
              // Chat composer: the paperclip opens the hidden file picker.
              if (e.target.closest("[data-attach-chat]")) {
                const inp = this.el.querySelector("[data-chat-file]")
                if (inp) inp.click()
                return
              }
              if (!e.target.closest("[data-capture-screenshot]")) return
              this.pushEvent("capture_start", {})
              try {
                const { toBlob } = await import("html-to-image")
                const blob = await toBlob(document.body, { cacheBust: true, pixelRatio: 1 })
                if (!blob) return this.pushEvent("screenshot_failed", {})
                // Hold the bytes locally; ask the server for a presigned URL.
                this.pendingBlob = blob
                this.pushEvent("request_screenshot_upload", { content_type: blob.type || "image/png" })
              } catch (err) {
                console.error("Screenshot capture failed:", err)
                this.pushEvent("screenshot_failed", {})
              }
            })

            // A chat file was picked (delegated — the input renders only when open).
            this.el.addEventListener("change", (e) => {
              const inp = e.target.closest("[data-chat-file]")
              if (!inp || !inp.files || !inp.files[0]) return
              const file = inp.files[0]
              this.pendingFile = file
              this.pushEvent("request_chat_upload", {
                content_type: file.type || "application/octet-stream",
                filename: file.name,
              })
              inp.value = ""
            })

            // Server handed back a presigned URL — PUT the bytes straight to S3.
            this.handleEvent("screenshot_upload_url", async ({ url, s3_key, content_type }) => {
              if (!this.pendingBlob) return
              try {
                const res = await fetch(url, {
                  method: "PUT",
                  body: this.pendingBlob,
                  headers: { "content-type": content_type },
                })
                if (!res.ok) throw new Error("upload failed: " + res.status)
                this.pushEvent("screenshot_uploaded", { s3_key: s3_key, content_type: content_type })
              } catch (err) {
                console.error("Screenshot upload failed:", err)
                this.pushEvent("screenshot_failed", {})
              } finally {
                this.pendingBlob = null
              }
            })

            this.handleEvent("chat_upload_url", async ({ url, s3_key, content_type }) => {
              if (!this.pendingFile) return
              const file = this.pendingFile
              try {
                const res = await fetch(url, {
                  method: "PUT",
                  body: file,
                  headers: { "content-type": content_type },
                })
                if (!res.ok) throw new Error("upload failed: " + res.status)
                this.pushEvent("chat_uploaded", {
                  s3_key: s3_key,
                  filename: file.name,
                  content_type: file.type || content_type,
                  size: file.size,
                })
              } catch (err) {
                console.error("Chat upload failed:", err)
                this.pushEvent("chat_upload_failed", {})
              } finally {
                this.pendingFile = null
              }
            })
          },
        }
      </script>

      <button
        type="button"
        phx-click="toggle"
        data-cms-widget-toggle
        data-test="widget-toggle"
        class="btn btn-primary btn-circle shadow-lg"
        aria-label="Support"
      >
        <.icon :if={!@open} name="hero-chat-bubble-oval-left" class="size-6" />
        <.icon :if={@open} name="hero-x-mark" class="size-6" />
      </button>

      <div
        :if={@open}
        data-test="widget-panel"
        class="absolute bottom-16 right-0 flex max-h-[32rem] w-80 flex-col overflow-hidden rounded-box border border-base-300 bg-base-100 shadow-xl"
      >
        <div class="shrink-0 border-b border-base-300 bg-base-200/50 px-4 py-3">
          <p class="font-semibold">How can we help?</p>
        </div>

        <div role="tablist" class="tabs tabs-bordered shrink-0">
          <button
            role="tab"
            phx-click="switch_tab"
            phx-value-tab="chat"
            data-test="tab-chat"
            class={["tab gap-1.5", @tab == :chat && "tab-active"]}
          >
            <.icon name="hero-chat-bubble-left-right" class="size-4" /> Chat
          </button>
          <button
            role="tab"
            phx-click="switch_tab"
            phx-value-tab="feedback"
            data-test="tab-feedback"
            class={["tab gap-1.5", @tab == :feedback && "tab-active"]}
          >
            <.icon name="hero-flag" class="size-4" /> Report a problem
          </button>
        </div>

        <div :if={@tab == :chat} data-test="chat-pane" class="flex min-h-0 flex-1 flex-col">
          <script :type={Phoenix.LiveView.ColocatedHook} name=".ChatScroll">
            export default {
              mounted() {
                this.scroll()
                this.observer = new MutationObserver(() => this.scroll())
                this.observer.observe(this.el, { childList: true, subtree: true })
              },
              destroyed() { this.observer && this.observer.disconnect() },
              scroll() { this.el.scrollTop = this.el.scrollHeight },
            }
          </script>
          <div
            id="cms-chat-scroll"
            phx-hook=".ChatScroll"
            data-test="chat-messages"
            class="flex-1 space-y-2 overflow-y-auto p-3"
          >
            <button
              :if={@messages != []}
              type="button"
              phx-click="load_older"
              data-test="chat-load-older"
              class="btn btn-ghost btn-xs w-full"
            >
              Load older messages
            </button>

            <p :if={@messages == []} class="py-8 text-center text-sm text-base-content/60">
              Send a message and our team will reply here.
            </p>

            <div
              :for={message <- @messages}
              data-test="chat-message"
              data-role={message["role"]}
              class={["chat", if(message["role"] == "user", do: "chat-end", else: "chat-start")]}
            >
              <div class="chat-bubble max-w-[15rem] break-words">
                <p :if={message["body"] not in [nil, ""]} class="whitespace-pre-wrap">
                  {message["body"]}
                </p>
                <div :for={att <- message_attachments(message)} class="mt-1">
                  <a :if={image_attachment?(att)} href={att["url"]} target="_blank" rel="noopener">
                    <img src={att["url"]} alt={att["filename"]} class="max-h-40 rounded" />
                  </a>
                  <a
                    :if={not image_attachment?(att)}
                    href={att["url"]}
                    target="_blank"
                    rel="noopener"
                    class="inline-flex items-center gap-1 text-sm underline"
                  >
                    <.icon name="hero-paper-clip" class="size-4" /> {att["filename"]}
                  </a>
                </div>
              </div>
            </div>
          </div>

          <div class="border-t border-base-300 p-3">
            <div
              :if={@pending_attachments != []}
              data-test="pending-attachments"
              class="mb-2 flex flex-wrap gap-1.5"
            >
              <span
                :for={att <- @pending_attachments}
                class="badge badge-ghost gap-1 max-w-[10rem]"
              >
                <.icon name="hero-paper-clip" class="size-3" />
                <span class="truncate">{att["filename"]}</span>
                <button
                  type="button"
                  phx-click="remove_attachment"
                  phx-value-key={att["s3_key"]}
                  aria-label="Remove attachment"
                  class="opacity-70 hover:opacity-100"
                >
                  ×
                </button>
              </span>
              <span :if={@chat_pending_meta} class="badge badge-ghost gap-1">
                <.icon name="hero-arrow-path" class="size-3 animate-spin" /> Uploading…
              </span>
            </div>

            <form phx-submit="send" phx-change="chat_change" data-test="chat-form" class="flex gap-2">
              <input type="file" data-chat-file data-test="chat-file" class="hidden" />
              <button
                type="button"
                data-attach-chat
                data-test="chat-attach"
                class="btn btn-ghost btn-sm btn-square"
                aria-label="Attach a file"
              >
                <.icon name="hero-paper-clip" class="size-4" />
              </button>
              <input
                type="text"
                name="message[body]"
                value={@chat_body}
                data-test="chat-input"
                placeholder="Type a message…"
                autocomplete="off"
                class="input input-bordered input-sm flex-1"
              />
              <button type="submit" class="btn btn-primary btn-sm" aria-label="Send">
                <.icon name="hero-paper-airplane" class="size-4" />
              </button>
            </form>
          </div>
        </div>

        <div
          :if={@tab == :feedback}
          data-test="feedback-pane"
          class="min-h-0 flex-1 overflow-y-auto p-4"
        >
          <div :if={@fb_submitted} class="py-6 text-center" data-test="feedback-thanks">
            <.icon name="hero-check-circle" class="mx-auto size-10 text-success" />
            <p class="mt-2 text-sm font-medium">Thanks — we've logged it.</p>
            <p class="text-xs text-base-content/60">Our team will take a look.</p>
            <button type="button" phx-click="reset_feedback" class="btn btn-ghost btn-xs mt-3">
              Report another
            </button>
          </div>

          <form
            :if={!@fb_submitted}
            phx-submit="submit_feedback"
            phx-change="fb_change"
            data-test="feedback-form"
            class="space-y-3"
          >
            <p class="text-xs text-base-content/60">
              Found a bug or have a request? Tell us what happened.
            </p>

            <div :if={@fb_error} class="alert alert-error p-2 text-xs" data-test="feedback-error">
              <span>{@fb_error}</span>
            </div>

            <label class="block">
              <span class="mb-1 block text-xs font-medium">Summary</span>
              <input
                type="text"
                name="title"
                value={@fb_title}
                data-test="feedback-title"
                placeholder="e.g. Save button does nothing"
                required
                class="input input-bordered input-sm w-full"
              />
            </label>

            <label class="block">
              <span class="mb-1 block text-xs font-medium">What happened?</span>
              <textarea
                name="description"
                data-test="feedback-description"
                placeholder="Steps, what you expected, what you saw…"
                rows="4"
                class="textarea textarea-bordered textarea-sm w-full"
              >{@fb_description}</textarea>
            </label>

            <label class="block">
              <span class="mb-1 block text-xs font-medium">Severity</span>
              <select name="severity" class="select select-bordered select-sm w-full">
                <option value="low" selected={@fb_severity == "low"}>Low — minor annoyance</option>
                <option value="medium" selected={@fb_severity == "medium"}>
                  Medium — something's off
                </option>
                <option value="high" selected={@fb_severity == "high"}>High — blocks my work</option>
                <option value="critical" selected={@fb_severity == "critical"}>
                  Critical — nothing works
                </option>
              </select>
            </label>

            <div
              :if={@screenshot_key}
              data-test="screenshot-attached"
              class="flex items-center justify-between rounded border border-base-300 bg-base-200/50 px-3 py-2 text-sm"
            >
              <span class="flex items-center gap-1.5">
                <.icon name="hero-check-circle" class="size-4 text-success" /> Screenshot attached
              </span>
              <button
                type="button"
                phx-click="remove_screenshot"
                class="btn btn-ghost btn-xs"
                aria-label="Remove screenshot"
              >
                ×
              </button>
            </div>

            <button
              :if={!@screenshot_key && @capturing}
              type="button"
              class="btn btn-ghost btn-xs w-full border-dashed border-base-300"
              disabled
            >
              <.icon name="hero-arrow-path" class="size-4 animate-spin" /> Attaching…
            </button>
            <button
              :if={!@screenshot_key && !@capturing}
              type="button"
              data-capture-screenshot
              data-test="capture-screenshot"
              class="btn btn-ghost btn-xs w-full border-dashed border-base-300"
            >
              <.icon name="hero-camera" class="size-4" /> Attach a screenshot
            </button>

            <button type="submit" class="btn btn-primary btn-sm w-full" data-test="feedback-submit">
              Send report
            </button>
          </form>
        </div>
      </div>
    </div>
    """
  end
end
