defmodule MetricFlow.CodeMySpec.WidgetClient do
  @moduledoc """
  Per-user Slipstream client bridging a logged-in user's support widget to
  CodeMySpec.

  Connects **server-side** with the project deploy key (the key never reaches
  the browser), joins `conversation:<user_id>`, and relays messages between
  CodeMySpec and the user's `SupportWidgetLive` over local PubSub. Chat and
  "Report a problem" both ride this one connection. Reconnects with backoff.
  Generated by `mix cms_gen.support_widget`.
  """

  use Slipstream

  require Logger

  alias MetricFlow.CodeMySpec.Widget

  def start_link(opts) do
    user_id = to_string(Keyword.fetch!(opts, :user_id))
    Slipstream.start_link(__MODULE__, Map.new(opts), name: Widget.via(user_id))
  end

  @impl Slipstream
  def init(opts) do
    user_id = to_string(opts.user_id)
    user_email = opts.user_email
    origin = Map.get(opts, :origin)

    case build_uri(user_id, user_email, origin) do
      {:ok, uri} ->
        socket =
          new_socket()
          |> assign(:user_id, user_id)
          |> assign(:user_email, user_email)
          |> assign(:origin, origin)
          |> assign(:topic, "conversation:#{user_id}")
          |> assign(:messages, [])
          |> assign(:connected, false)
          |> assign(:reconnect_attempts, 0)
          |> connect!(uri: uri)

        {:ok, socket}

      {:error, reason} ->
        Logger.warning("[WidgetClient] cannot connect: #{inspect(reason)}")
        :ignore
    end
  end

  @impl Slipstream
  def handle_connect(socket) do
    {:ok, join(socket, socket.assigns.topic)}
  end

  @impl Slipstream
  def handle_join(_topic, _reply, socket) do
    socket = socket |> assign(:reconnect_attempts, 0) |> assign(:connected, true)
    broadcast(socket, {:connected, true})
    {:ok, socket}
  end

  @impl Slipstream
  def handle_message(_topic, "new_message", payload, socket) do
    messages = socket.assigns.messages ++ [payload]
    socket = assign(socket, :messages, messages)
    broadcast(socket, {:new_message, payload})
    {:ok, socket}
  end

  def handle_message(_topic, _event, _payload, socket), do: {:ok, socket}

  # Reply to a `load_older` push: prepend the previous page and re-broadcast.
  @impl Slipstream
  def handle_reply(_ref, {:ok, %{"messages" => older}}, socket) when is_list(older) do
    messages = older ++ socket.assigns.messages
    socket = assign(socket, :messages, messages)
    broadcast(socket, {:messages, messages})
    {:ok, socket}
  end

  # Reply to a presigned-upload request. The key's prefix says which one:
  # `chat/…` is a chat attachment, `issues/…` is a report screenshot.
  def handle_reply(_ref, {:ok, %{"upload_url" => url, "s3_key" => "chat/" <> _ = key}}, socket) do
    broadcast(socket, {:chat_upload, url, key})
    {:ok, socket}
  end

  def handle_reply(_ref, {:ok, %{"upload_url" => url, "s3_key" => key}}, socket) do
    broadcast(socket, {:screenshot_upload, url, key})
    {:ok, socket}
  end

  def handle_reply(_ref, _reply, socket), do: {:ok, socket}

  @impl Slipstream
  def handle_call(:state, _from, socket) do
    {:reply, %{messages: socket.assigns.messages, connected: socket.assigns[:connected] == true},
     socket}
  end

  # The site this client told CodeMySpec it was connecting from. `origin` is
  # sent once, at connect, so `Widget.ensure_started/3` has to ask before
  # deciding whether a running client can be reused for a different site.
  def handle_call(:origin, _from, socket) do
    {:reply, socket.assigns[:origin], socket}
  end

  @impl Slipstream
  def handle_cast({:send_message, body, attachments}, socket) do
    push(socket, socket.assigns.topic, "send_message", %{
      "body" => body,
      "attachments" => attachments
    })

    {:noreply, socket}
  end

  def handle_cast({:load_older, before}, socket) do
    push(socket, socket.assigns.topic, "load_older", %{"before" => before})
    {:noreply, socket}
  end

  def handle_cast({:request_screenshot_upload, content_type}, socket) do
    push(socket, socket.assigns.topic, "request_screenshot_upload", %{"content_type" => content_type})
    {:noreply, socket}
  end

  def handle_cast({:request_chat_upload, content_type, filename}, socket) do
    push(socket, socket.assigns.topic, "request_chat_upload", %{
      "content_type" => content_type,
      "filename" => filename
    })

    {:noreply, socket}
  end

  # "Report a problem" rides the same deploy-key connection as chat — pushed to
  # CodeMySpec as a `submit_feedback` event, which files an issue on the project.
  def handle_cast({:submit_feedback, payload}, socket) do
    push(socket, socket.assigns.topic, "submit_feedback", payload)
    {:noreply, socket}
  end

  @impl Slipstream
  def handle_disconnect(reason, socket) do
    attempts = socket.assigns.reconnect_attempts
    delay = backoff(attempts)
    Logger.info("[WidgetClient] disconnected (#{inspect(reason)}), reconnecting in #{delay}ms")
    Process.send_after(self(), :reconnect, delay)

    # Say so rather than reconnecting silently. A widget that looks live while
    # its backend is gone accepts a message and drops it, and the visitor
    # believes they were heard — worse than showing unavailable.
    socket = socket |> assign(:connected, false) |> assign(:reconnect_attempts, attempts + 1)
    broadcast(socket, {:connected, false})
    {:ok, socket}
  end

  @impl Slipstream
  def handle_info(:reconnect, socket) do
    case build_uri(socket.assigns.user_id, socket.assigns.user_email, socket.assigns.origin) do
      {:ok, uri} ->
        {:ok, socket} = connect(socket, uri: uri)
        {:noreply, socket}

      {:error, _reason} ->
        Process.send_after(self(), :reconnect, backoff(socket.assigns.reconnect_attempts))
        {:noreply, socket}
    end
  end

  defp broadcast(socket, message) do
    Phoenix.PubSub.broadcast(
      MetricFlow.PubSub,
      Widget.topic(socket.assigns.user_id),
      message
    )
  end

  defp backoff(attempts), do: min(trunc(:math.pow(2, attempts) * 1000), 10_000)

  # The deploy key is self-identifying on CodeMySpec (blind index), so the
  # widget presents only the key — no project id.
  defp build_uri(user_id, user_email, origin) do
    base = Application.get_env(:metric_flow, :codemyspec_widget_url)
    deploy_key = Application.get_env(:metric_flow, :deploy_key)

    if present?(base) and present?(deploy_key) do
      query =
        URI.encode_query(%{
          "deploy_key" => deploy_key,
          "user_id" => user_id,
          "user_email" => user_email,
          # Where this app is actually running. CodeMySpec stamps it on the
          # messages that arrive and uses it to tell a widget that works for
          # visitors apart from one that has only ever worked on the author's
          # laptop — the same deploy key serves both.
          #
          # Handed in by the caller rather than read from the endpoint here:
          # this module is in the app namespace and the endpoint is in the web
          # one, and reaching across is a boundary violation the compiler
          # reports on every build of the generated project.
          "origin" => origin,
          "vsn" => "2.0.0"
        })

      {:ok, "#{base}/websocket?#{query}"}
    else
      {:error, :not_configured}
    end
  end

  defp present?(nil), do: false
  defp present?(""), do: false
  defp present?(_), do: true
end
