defmodule MetricFlow.CodeMySpec.Widget do
  @moduledoc """
  Public interface to a user's support `WidgetClient`. Starts one Slipstream
  client per user on demand (under the app's DynamicSupervisor, keyed in the
  Registry) and exposes chat send / pagination / feedback / state to
  `SupportWidgetLive`. Generated by `mix cms_gen.support_widget`.
  """

  alias MetricFlow.CodeMySpec.WidgetClient

  @registry MetricFlow.CodeMySpec.WidgetRegistry
  @supervisor MetricFlow.CodeMySpec.WidgetSupervisor

  @doc "Registry `:via` tuple for a user's client process."
  def via(user_id), do: {:via, Registry, {@registry, to_string(user_id)}}

  @doc "PubSub topic SupportWidgetLive subscribes to for a user's message updates."
  def topic(user_id), do: "codemyspec:widget:#{user_id}"

  @doc """
  Starts the user's client if not already running. Idempotent.

  A client already running with a *different* origin is replaced rather than
  reused. `origin` is what tells CodeMySpec which site a message came from, and
  it is sent once, when the socket connects — so a client started earlier
  without one goes on reporting nothing forever, and `{:already_started, pid}`
  quietly discarded the origin the caller had just supplied.

  That is how a widget that was installed, connected and delivering messages
  still could not be proven: the messages arrived with no origin, so nothing
  could attribute them to the site that sent them.
  """
  def ensure_started(user_id, user_email, origin \\ nil) do
    spec =
      {WidgetClient, [user_id: to_string(user_id), user_email: user_email, origin: origin]}

    case DynamicSupervisor.start_child(@supervisor, spec) do
      {:ok, pid} ->
        {:ok, pid}

      {:error, {:already_started, pid}} ->
        restart_if_origin_changed(pid, spec, origin)

      :ignore ->
        {:error, :not_configured}

      other ->
        other
    end
  end

  defp restart_if_origin_changed(pid, spec, origin) do
    if origin in [nil, running_origin(pid)] do
      {:ok, pid}
    else
      DynamicSupervisor.terminate_child(@supervisor, pid)

      case DynamicSupervisor.start_child(@supervisor, spec) do
        {:ok, new_pid} -> {:ok, new_pid}
        {:error, {:already_started, existing}} -> {:ok, existing}
        other -> other
      end
    end
  end

  # A client that cannot answer is one being replaced anyway, so an unreadable
  # origin reads as "different" rather than raising.
  defp running_origin(pid) do
    case GenServer.call(pid, :origin, 2_000) do
      origin when is_binary(origin) -> origin
      _ -> nil
    end
  catch
    :exit, _ -> nil
  end

  @doc "Current accumulated messages for the user (for a freshly-mounted widget)."
  def state(user_id) do
    GenServer.call(via(user_id), :state)
  catch
    # No client running is not "fine, no messages" — it is the widget being
    # unavailable, and the widget has to be able to say so.
    :exit, _ -> %{messages: [], connected: false}
  end

  def send_message(user_id, body, attachments \\ []),
    do: cast(user_id, {:send_message, body, attachments})

  def load_older(user_id, before), do: cast(user_id, {:load_older, before})

  @doc "Ask CodeMySpec for a presigned S3 URL to upload a screenshot to."
  def request_screenshot_upload(user_id, content_type),
    do: cast(user_id, {:request_screenshot_upload, content_type})

  @doc "Ask CodeMySpec for a presigned S3 URL to upload a chat attachment to."
  def request_chat_upload(user_id, content_type, filename),
    do: cast(user_id, {:request_chat_upload, content_type, filename})

  @doc "Report a problem (title/description/severity) — filed as a CodeMySpec issue."
  def submit_feedback(user_id, payload), do: cast(user_id, {:submit_feedback, payload})

  defp cast(user_id, message) do
    GenServer.cast(via(user_id), message)
  catch
    :exit, _ -> :ok
  end
end
